// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package testproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Student struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	SchoolId             int32    `protobuf:"varint,2,opt,name=schoolId,proto3" json:"schoolId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (dst *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(dst, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *Student) GetSchoolId() int32 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Tel                  *Tel     `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetTel() *Tel {
	if m != nil {
		return m.Tel
	}
	return nil
}

type Tel struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tel) Reset()         { *m = Tel{} }
func (m *Tel) String() string { return proto.CompactTextString(m) }
func (*Tel) ProtoMessage()    {}
func (*Tel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}
func (m *Tel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tel.Unmarshal(m, b)
}
func (m *Tel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tel.Marshal(b, m, deterministic)
}
func (dst *Tel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tel.Merge(dst, src)
}
func (m *Tel) XXX_Size() int {
	return xxx_messageInfo_Tel.Size(m)
}
func (m *Tel) XXX_DiscardUnknown() {
	xxx_messageInfo_Tel.DiscardUnknown(m)
}

var xxx_messageInfo_Tel proto.InternalMessageInfo

func (m *Tel) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Student)(nil), "testproto.Student")
	proto.RegisterType((*Person)(nil), "testproto.Person")
	proto.RegisterType((*Tel)(nil), "testproto.Tel")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0x41, 0xcb, 0x82, 0x40,
	0x10, 0x86, 0xf1, 0xdb, 0xcf, 0x2d, 0x47, 0x88, 0x9a, 0x43, 0x48, 0x10, 0x88, 0x27, 0xbb, 0x78,
	0xa8, 0x5f, 0xd1, 0x4d, 0x36, 0xff, 0x80, 0xe6, 0x50, 0x87, 0x75, 0x57, 0x74, 0xfc, 0xff, 0xe1,
	0x24, 0xd2, 0xed, 0x19, 0xde, 0x67, 0xde, 0x17, 0xe2, 0xce, 0xb7, 0x64, 0x8b, 0x7e, 0xf0, 0xec,
	0x31, 0x62, 0x1a, 0x59, 0x30, 0x2b, 0x61, 0xf3, 0xe0, 0xa9, 0x25, 0xc7, 0x78, 0x01, 0xdd, 0xd3,
	0x30, 0x7a, 0x97, 0x04, 0x69, 0x90, 0xc7, 0xd7, 0x43, 0xb1, 0x6a, 0x45, 0x29, 0x81, 0x59, 0x04,
	0x3c, 0xc1, 0x76, 0x7c, 0xbe, 0xbd, 0xb7, 0xf7, 0x36, 0xf9, 0x4b, 0x83, 0x3c, 0x34, 0xeb, 0x9d,
	0x95, 0xa0, 0xbf, 0x36, 0x22, 0xfc, 0xbb, 0xba, 0x23, 0xa9, 0x8b, 0x8c, 0x30, 0xee, 0x41, 0xd5,
	0x2f, 0x5a, 0x9e, 0x66, 0xc4, 0x14, 0x14, 0x93, 0x4d, 0x94, 0x6c, 0xee, 0x7e, 0x36, 0x2b, 0xb2,
	0x66, 0x8e, 0xb2, 0x33, 0xa8, 0x8a, 0x2c, 0x1e, 0x41, 0xbb, 0xa9, 0x6b, 0x68, 0x90, 0xc2, 0xd0,
	0x2c, 0x57, 0xa3, 0x45, 0xbf, 0x7d, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x6a, 0x32, 0x95, 0xe3,
	0x00, 0x00, 0x00,
}
